# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Tests for the invariant-citation gate.

The gate exists because ``security/INVARIANTS.md`` pins what enforces each
kernel invariant by file and line, and a pointer that drifts keeps reading as
evidence. The tests pin the citation grammar, the definition rule, the test
rule that separates a named function from a named test, and the rewrite that
puts a moved pointer back on the item it meant.
"""

from __future__ import annotations

import pathlib
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import invariants  # noqa: E402
import pytest  # noqa: E402

ROOT = SCRIPT_DIR.parents[1]

SOURCE = """\
pub enum ExecutionState {
    Claimed,
    Unknown,
    Failed,
}

pub const fn is_valid_lifecycle_transition(
    current: ExecutionState,
    next: ExecutionState,
) -> bool {
    true
}

impl VerifiedGrant {
    pub fn binds(&self, request: &AuthorityRequest) -> bool {
        let _ = request;
        true
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn mismatched_grants_cancel_the_pre_dispatch_action() {}

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn sealing_consumes_the_builder() {}

    fn a_helper_nobody_runs() {}
}
"""

DOCUMENT = """\
# Invariants

Line numbers are pointers regenerated by `scripts/tcb/invariants.py --write`.

## K-005 — UNKNOWN does not mean FAILED

**Enforced by** `ExecutionState::Unknown` vs `ExecutionState::Failed`
(`crates/ledger/src/lib.rs:3`) and the recovery decisions that branch on them.

**Verified by** `mismatched_grants_cancel_the_pre_dispatch_action`
(`crates/ledger/src/lib.rs`).

## K-016 — a possibly-dispatched action enters UNKNOWN

**Enforced by** `state_for_error`. The `match` is total: `FAILED` requires
exactly `NotDispatched`, and the kernel routes through
`is_valid_lifecycle_transition` (`crates/ledger/src/lib.rs:7`) instead of
terminalizing.
"""


def tree(tmp_path: pathlib.Path, source: str = SOURCE) -> pathlib.Path:
    target = tmp_path / "crates" / "ledger" / "src"
    target.mkdir(parents=True)
    (target / "lib.rs").write_text(source)
    return tmp_path


def test_a_path_citation_must_exist(tmp_path: pathlib.Path) -> None:
    tree(tmp_path)
    problems = invariants.check(tmp_path, "**Enforced by** `binds` (`crates/ledger/src/missing.rs`).")

    assert problems == ["crates/ledger/src/missing.rs cited on line 1 does not exist"]


def test_a_line_pointer_lands_on_the_definition(tmp_path: pathlib.Path) -> None:
    tree(tmp_path)

    problems = invariants.check(
        tmp_path,
        "**Enforced by** `VerifiedGrant::binds` (`crates/ledger/src/lib.rs:15`).",
    )

    assert problems == []


def test_a_stale_line_pointer_is_reported_with_the_definition(tmp_path: pathlib.Path) -> None:
    tree(tmp_path)

    problems = invariants.check(
        tmp_path,
        "**Enforced by** `VerifiedGrant::binds` (`crates/ledger/src/lib.rs:3`).",
    )

    assert len(problems) == 1
    assert "binds" in problems[0] and "[15]" in problems[0]


def test_an_enforced_by_clause_may_describe_neighbouring_states(tmp_path: pathlib.Path) -> None:
    """`FAILED` and `NotDispatched` describe; the citation claims the last item."""
    tree(tmp_path)

    problems = invariants.check(tmp_path, DOCUMENT)

    assert problems == []


def test_a_cited_group_with_no_definition_there_is_reported(tmp_path: pathlib.Path) -> None:
    tree(tmp_path)

    problems = invariants.check(
        tmp_path,
        "**Enforced by** `absent` (`crates/ledger/src/lib.rs`).",
    )

    assert len(problems) == 1
    assert "absent" in problems[0]


def test_a_verified_by_name_must_carry_a_test_attribute(tmp_path: pathlib.Path) -> None:
    """`fn name` without `#[test]` is a function, not a test."""
    tree(tmp_path)

    problems = invariants.check(
        tmp_path,
        "**Verified by** `a_helper_nobody_runs` (`crates/ledger/src/lib.rs`).",
    )

    assert len(problems) == 1
    assert "a_helper_nobody_runs" in problems[0]


def test_attribute_chains_between_the_test_attribute_and_fn_count(
    tmp_path: pathlib.Path,
) -> None:
    tree(tmp_path)

    problems = invariants.check(
        tmp_path,
        "**Verified by** `sealing_consumes_the_builder` (`crates/ledger/src/lib.rs`).",
    )

    assert problems == []


def test_a_verified_by_name_without_a_path_resolves_in_the_workspace(
    tmp_path: pathlib.Path,
) -> None:
    tree(tmp_path)

    problems = invariants.check(tmp_path, "**Verified by** `a_test_that_was_renamed`.")

    assert len(problems) == 1
    assert "a_test_that_was_renamed" in problems[0]


def test_write_repins_a_stale_line_to_the_definition(tmp_path: pathlib.Path) -> None:
    tree(tmp_path)
    document = "**Enforced by** `VerifiedGrant::binds` (`crates/ledger/src/lib.rs:3`)."

    rewritten, made = invariants.write(tmp_path, document)

    assert made
    assert "crates/ledger/src/lib.rs:15" in rewritten
    assert invariants.check(tmp_path, rewritten) == []


def test_write_leaves_a_correct_line_alone(tmp_path: pathlib.Path) -> None:
    tree(tmp_path)
    document = "**Enforced by** `VerifiedGrant::binds` (`crates/ledger/src/lib.rs:15`)."

    rewritten, made = invariants.write(tmp_path, document)

    assert made == []
    assert rewritten == document


def test_write_refuses_to_guess_between_definitions(tmp_path: pathlib.Path) -> None:
    tree(tmp_path)
    document = "**Enforced by** `Unknown` vs `Failed` (`crates/ledger/src/lib.rs:9`)."

    with pytest.raises(invariants.InvariantError):
        invariants.write(tmp_path, document)


def test_write_accepts_a_line_landing_on_any_claimed_symbol(
    tmp_path: pathlib.Path,
) -> None:
    tree(tmp_path)

    rewritten, made = invariants.write(tmp_path, DOCUMENT)

    assert made == []
    assert rewritten == DOCUMENT


def test_a_bare_path_mention_outside_claims_is_still_checked(
    tmp_path: pathlib.Path,
) -> None:
    tree(tmp_path)

    problems = invariants.check(tmp_path, "See `crates/ledger/src/missing.rs` here.")

    assert problems == ["crates/ledger/src/missing.rs cited on line 1 does not exist"]


def test_repository_invariant_document_resolves() -> None:
    """The document this gate guards stays honest against the real tree."""
    document = (ROOT / "security" / "INVARIANTS.md").read_text()

    assert invariants.check(ROOT, document) == []
