#!/usr/bin/env python3
"""Verify the NEMO runtime transfer manifest without a Go toolchain.

This is the consumer-side mirror of `cmd/nemo-runtime-digest -manifest`:
same digest definition, same checks, same failure semantics — written in
stdlib-only Python 3 so a downstream consumer of the distribution can
verify what it was given without building anything.

What it verifies, in order:

  1. Computed identity — the shipped tree's regular-file digest, file
     count, declared runtime version, and exclusion set must equal the
     manifest's declared values.
  2. Inventory — every declared added workspace member is in the
     vendored Cargo.toml `members` array, and every declared modified or
     added path exists.
  3. Binaries — every declared binary has its source inside the tree,
     the owning package declares it (a `[[bin]]` entry or Cargo's
     `src/bin/<name>.rs` auto-discovery), a declared `[[bin]]` path is
     the source the manifest names, and every declared feature exists.
  4. Provenance record — the generated blocks inside the tree's
     TRANSFER-PROVENANCE.md render exactly what the manifest declares.
  5. Source identity and delta — when `source.path` is present on disk,
     the source tree's identity matches its declaration and the declared
     delta (modifications / added paths / removed paths) is the complete
     difference between the trees. A standalone checkout does not carry
     the source; its absence is reported, not treated as a pass.

Usage:

    python3 scripts/verify-nemo-transfer.py [MANIFEST]

MANIFEST defaults to runtimes/nemo-transfer-manifest.json relative to
the repository root (the parent of this script's directory). Tree and
source paths in the manifest are resolved relative to that root, the
same as the Go tool.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import stat
import sys

# Directories that are build output or working-copy state rather than
# source — the same set the Go tool excludes. A digest that moved when
# someone ran `cargo build` would bind nothing.
EXCLUDED = {"target", ".git", "node_modules", ".venv", ".uv-cache", "__pycache__"}

# The in-tree transfer record carrying the generated blocks.
PROVENANCE_DOC = "TRANSFER-PROVENANCE.md"

DELTA_BLOCK_BEGIN = (
    "<!-- BEGIN GENERATED TRANSFER DELTA — regenerated by "
    "`nemo-runtime-digest -update`; do not edit by hand -->"
)
DELTA_BLOCK_END = "<!-- END GENERATED TRANSFER DELTA -->"
SOURCE_BLOCK_BEGIN = (
    "<!-- BEGIN GENERATED SOURCE IDENTITY — regenerated by "
    "`nemo-runtime-digest -update`; do not edit by hand -->"
)
SOURCE_BLOCK_END = "<!-- END GENERATED SOURCE IDENTITY -->"

MEMBERS_ARRAY = re.compile(r"(?m)^members\s*=\s*\[([^\]]*)\]")
QUOTED_ENTRY = re.compile(r'"([^"]+)"')


class VerifyError(Exception):
    """A verification failure — printed to stderr, exit 1."""


def _fs(path: str) -> str:
    """Decode a filesystem path the way Go carries it: raw bytes round-tripped."""
    return os.fsdecode(path)


def source_files(root: str) -> list[str]:
    """The tree's regular files as `./`-prefixed slash paths.

    Mirrors the Go tool's sourceFiles: directory walk, excluded names
    pruned below the root only, regular files only (a symlink to a file
    is a symlink, not a file).
    """
    paths = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDED]
        for name in filenames:
            full = os.path.join(dirpath, name)
            if not stat.S_ISREG(os.lstat(full).st_mode):
                continue
            rel = os.path.relpath(full, root)
            paths.append("./" + _fs(rel).replace(os.sep, "/"))
    return paths


def file_digest(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def digest_runtime(root: str) -> dict:
    """The verifiable identity of a runtime tree — mirrors digestRuntime."""
    if not os.path.isdir(root):
        raise VerifyError(f"the NeMo Relay runtime tree is missing at {root}")

    paths = sorted(source_files(root))
    if not paths:
        raise VerifyError(f"the NeMo Relay runtime tree at {root} contains no source files")

    outer = hashlib.sha256()
    for path in paths:
        full = os.path.join(root, *path.removeprefix("./").split("/"))
        # The record line is `sha256(content) + two spaces + path + \n`,
        # byte-identical to the Go tool's fmt.Fprintf.
        outer.update(f"{file_digest(full)}  {path}\n".encode("utf-8", "surrogateescape"))

    version = workspace_version(root)
    return {
        "nemo_runtime_sha256": outer.hexdigest(),
        "runtime_version": version,
        "tree": root,
        "file_count": len(paths),
        "excluded": sorted(EXCLUDED),
    }


def _section_value(text: str, section: str, key: str) -> str:
    """Extract `key = "value"` from a TOML section by line scan —
    the same line-oriented read the Go tool performs."""
    in_section = False
    for line in text.split("\n"):
        trimmed = line.strip()
        if trimmed.startswith("["):
            in_section = trimmed == section
            continue
        if not in_section:
            continue
        if trimmed.startswith(key):
            value = trimmed[len(key):].strip()
            if value.startswith("="):
                return value[1:].strip().strip('"')
    return ""


def workspace_version(root: str) -> str:
    """The `[workspace.package] version` the tree declares."""
    try:
        with open(os.path.join(root, "Cargo.toml"), encoding="utf-8") as f:
            text = f.read()
    except OSError as e:
        raise VerifyError(f"{root}/Cargo.toml: {e}")
    version = _section_value(text, "[workspace.package]", "version")
    if not version:
        raise VerifyError(f"the NeMo Relay workspace manifest at {root} declares no version")
    return version


def declared_workspace_members(tree: str) -> list[str]:
    """The quoted entries of the workspace `members` array."""
    try:
        with open(os.path.join(tree, "Cargo.toml"), encoding="utf-8") as f:
            text = f.read()
    except OSError as e:
        raise VerifyError(f"{tree}/Cargo.toml: {e}")
    block = MEMBERS_ARRAY.search(text)
    if not block:
        raise VerifyError(f"{tree}/Cargo.toml declares no members array")
    return QUOTED_ENTRY.findall(block.group(1))


def package_name(manifest_text: str) -> str:
    return _section_value(manifest_text, "[package]", "name")


def package_declares_feature(manifest_text: str, feature: str) -> bool:
    in_features = False
    for line in manifest_text.split("\n"):
        trimmed = line.strip()
        if trimmed.startswith("["):
            in_features = trimmed == "[features]"
            continue
        if not in_features or not trimmed or trimmed.startswith("#"):
            continue
        if "=" in trimmed:
            name, _, _ = trimmed.partition("=")
            if name.strip() == feature:
                return True
    return False


def declared_binary_path(manifest_text: str, binary: str) -> tuple[str, bool]:
    """The package-relative path a [[bin]] declares, and whether one exists."""
    section = ""
    block: list[str] = []
    declared_path = ""
    declared = False

    def flush() -> None:
        nonlocal declared_path, declared
        if section != "[[bin]]":
            return
        name = path = ""
        for line in block:
            trimmed = line.strip()
            for key in ("name", "path"):
                if trimmed.startswith(key):
                    value = trimmed[len(key):].strip()
                    if value.startswith("="):
                        value = value[1:].strip().strip('"')
                        if key == "name":
                            name = value
                        else:
                            path = value
        if name == binary:
            declared = True
            declared_path = path

    for line in manifest_text.split("\n"):
        trimmed = line.strip()
        if trimmed.startswith("["):
            flush()
            section = trimmed
            block = []
            continue
        block.append(line)
    flush()
    return declared_path, declared


def package_manifest_for(root: str, source: str) -> tuple[str, str]:
    """Walk up from a source file to the Cargo.toml of its package."""
    root = os.path.normpath(root)
    directory = os.path.dirname(os.path.normpath(source))
    while True:
        candidate = os.path.join(directory, "Cargo.toml")
        if os.path.isfile(candidate):
            return candidate, directory
        if directory == root:
            break
        parent = os.path.dirname(directory)
        if parent == directory or not (
            directory.startswith(root + os.sep)
        ):
            break
        directory = parent
    raise VerifyError(f"no Cargo.toml found above {source}")


def tree_entries(root: str) -> dict[str, str]:
    """Every non-directory entry under root mapped to a content identity.

    Broader than source_files on purpose: a retargeted symlink must
    surface in the delta even though the file digest never sees links.
    """
    entries: dict[str, str] = {}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDED]
        for name in filenames:
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            st = os.lstat(full)
            if stat.S_ISREG(st.st_mode):
                entries[rel] = "file:" + file_digest(full)
            elif stat.S_ISLNK(st.st_mode):
                entries[rel] = "symlink:" + os.readlink(full)
            else:
                entries[rel] = "other:" + stat.filemode(st.st_mode)
        # A symlinked directory lands in dirnames — WalkDir reports it as
        # a non-directory entry, so record it like a file-level symlink.
        for name in list(dirnames):
            full = os.path.join(dirpath, name)
            if stat.S_ISLNK(os.lstat(full).st_mode):
                rel = os.path.relpath(full, root).replace(os.sep, "/")
                entries[rel] = "symlink:" + os.readlink(full)
                dirnames.remove(name)
    return entries


def diff_trees(source: str, vendored: str) -> dict[str, list[str]]:
    """The complete difference between the source copy and the vendored tree."""
    src = tree_entries(source)
    vend = tree_entries(vendored)
    modified = sorted(p for p, s in src.items() if p in vend and vend[p] != s)
    removed = sorted(p for p in src if p not in vend)
    added = sorted(p for p in vend if p not in src)
    return {"modified": modified, "added": added, "removed": removed}


def added_path_covers(declared: str, actual: str) -> bool:
    """A declared added_paths entry covers an actual addition: exact
    match, or a trailing-slash directory prefix covering a subtree."""
    if declared.endswith("/"):
        return actual.startswith(declared)
    return actual == declared


def verify_inventory(manifest_path: str, manifest: dict) -> None:
    """Structural claims: declared members are members, declared paths exist."""
    added_members = manifest.get("workspace_members_added") or []
    if added_members:
        members = declared_workspace_members(manifest["tree"])
        for member in added_members:
            if member not in members:
                raise VerifyError(
                    f"{manifest_path} declares workspace member {member!r}, but "
                    f"{manifest['tree']}/Cargo.toml does not list it"
                )
    tree = manifest["tree"]
    for path in list(manifest.get("local_modifications") or []) + list(
        manifest.get("added_paths") or []
    ):
        if not os.path.lexists(os.path.join(tree, path.rstrip("/"))):
            raise VerifyError(
                f"{manifest_path} declares {path!r}, but {tree}/{path.rstrip('/')} does not exist"
            )


def verify_binaries(manifest_path: str, manifest: dict) -> None:
    """Every declared binary must be one the tree can actually build."""
    tree = manifest["tree"]
    root = os.path.normpath(tree)
    for binary in manifest.get("binaries") or []:
        source = os.path.join(tree, binary["source"])
        if not os.path.normpath(source).startswith(root + os.sep):
            raise VerifyError(
                f"{manifest_path} declares {binary['binary']} with a source "
                f"outside the tree: {binary['source']}"
            )
        if not os.path.isfile(source):
            raise VerifyError(
                f"{manifest_path} declares the {binary['binary']} binary at {source}, "
                "but the source does not exist — a declared binary with no "
                "source is a release defect"
            )
        package_manifest, package_dir = package_manifest_for(root, source)
        try:
            with open(package_manifest, encoding="utf-8") as f:
                text = f.read()
        except OSError as e:
            raise VerifyError(f"{package_manifest}: {e}")
        if package_name(text) != binary["package"]:
            raise VerifyError(
                f"{manifest_path} declares the {binary['binary']} binary in package "
                f"{binary['package']!r}, but {package_manifest} declares package "
                f"{package_name(text)!r}"
            )
        declared_path, declared = declared_binary_path(text, binary["binary"])
        if not declared:
            auto = os.path.join(package_dir, "src", "bin", binary["binary"] + ".rs")
            if not os.path.isfile(auto):
                raise VerifyError(
                    f"{manifest_path} declares the {binary['binary']} binary, but "
                    f"{package_manifest} neither declares a [[bin]] entry for it "
                    f"nor provides {auto}"
                )
            continue
        if declared_path:
            package_relative = os.path.relpath(source, package_dir).replace(os.sep, "/")
            if package_relative != declared_path:
                raise VerifyError(
                    f"{manifest_path} declares the {binary['binary']} binary at "
                    f"{binary['source']}, but {package_manifest} declares its "
                    f"path as {declared_path!r}"
                )
        for feature in binary.get("features") or []:
            if not package_declares_feature(text, feature):
                raise VerifyError(
                    f"{manifest_path} declares the {binary['binary']} binary with "
                    f"feature {feature!r}, but {package_manifest} declares no such feature"
                )


def render_delta_block(manifest: dict) -> str:
    """The manifest's declared delta as the canonical generated block."""
    out = [DELTA_BLOCK_BEGIN, "", "| Kind | Path |", "| --- | --- |"]
    for kind, key in (
        ("modified", "local_modifications"),
        ("added", "added_paths"),
        ("removed", "removed_paths"),
    ):
        paths = manifest.get(key) or []
        if not paths:
            out.append(f"| {kind} | — |")
        else:
            out.extend(f"| {kind} | `{p}` |" for p in paths)
    out.extend(["", DELTA_BLOCK_END])
    return "\n".join(out)


def render_source_block(source: dict) -> str:
    """The manifest's declared source identity as the generated block."""
    return "\n".join(
        [
            SOURCE_BLOCK_BEGIN,
            "",
            f"{source['file_count']} files. Digest over the sorted `sha256(path, content)` records of the",
            "source tree as it was copied, before any local modification:",
            "",
            "```text",
            source["sha256"],
            "```",
            "",
            SOURCE_BLOCK_END,
        ]
    )


def splice_generated(doc: str, begin: str, end: str, rendered: str, name: str, doc_path: str) -> str:
    """Replace the marker-delimited block (markers included) with rendered."""
    if doc.count(begin) > 1 or doc.count(end) > 1:
        raise VerifyError(
            f"{doc_path} carries duplicate {name} markers — run "
            "`nemo-runtime-digest -update` after removing the copy"
        )
    begin_idx = doc.find(begin)
    end_idx = doc.find(end)
    if begin_idx < 0 or end_idx < 0 or begin_idx > end_idx:
        raise VerifyError(
            f"{doc_path} carries no generated {name} — run "
            "`nemo-runtime-digest -update` to regenerate it"
        )
    return doc[:begin_idx] + rendered + doc[end_idx + len(end):]


def check_provenance_doc(tree: str, manifest: dict) -> None:
    """The generated blocks must render exactly what the manifest declares."""
    doc_path = os.path.join(tree, PROVENANCE_DOC)
    try:
        with open(doc_path, encoding="utf-8") as f:
            doc = f.read()
    except OSError as e:
        raise VerifyError(f"the provenance record {doc_path}: {e}")

    stale = []
    reconciled = splice_generated(
        doc, DELTA_BLOCK_BEGIN, DELTA_BLOCK_END, render_delta_block(manifest), "delta block", doc_path
    )
    if reconciled != doc:
        stale.append("delta")
    source = manifest.get("source")
    if source:
        spliced = splice_generated(
            reconciled, SOURCE_BLOCK_BEGIN, SOURCE_BLOCK_END,
            render_source_block(source), "source-identity block", doc_path,
        )
        if spliced != reconciled:
            stale.append("source-identity")
        reconciled = spliced
    elif SOURCE_BLOCK_BEGIN in reconciled:
        raise VerifyError(
            f"{doc_path} carries a generated source-identity block, but the "
            "manifest declares no source — the record and the declaration disagree"
        )
    if stale:
        which = " and ".join(stale) + (" blocks do" if len(stale) > 1 else " block does")
        raise VerifyError(
            f"{doc_path} is stale: its generated {which} not match the manifest — "
            "regenerate with `nemo-runtime-digest -manifest runtimes/nemo-transfer-manifest.json -update`"
        )


def verify_delta(manifest: dict) -> dict[str, list[str]]:
    """The declared inventory must be the complete difference — every
    undeclared or stale entry is a failure."""
    delta = diff_trees(manifest["source"]["path"], manifest["tree"])

    problems = []
    declared_mod = sorted(manifest.get("local_modifications") or [])
    declared_added = manifest.get("added_paths") or []
    declared_removed = sorted(manifest.get("removed_paths") or [])

    for path in delta["modified"]:
        if path not in declared_mod:
            problems.append(f"undeclared modification: {path}")
    for path in declared_mod:
        if path not in delta["modified"]:
            problems.append(f"declared modification {path} is identical to the source (stale declaration)")
    for path in delta["added"]:
        if not any(added_path_covers(d, path) for d in declared_added):
            problems.append(f"undeclared addition: {path}")
    for declared in declared_added:
        if not any(added_path_covers(declared, path) for path in delta["added"]):
            problems.append(f"declared added path {declared} covers no actual addition (stale declaration)")
    for path in delta["removed"]:
        if path not in declared_removed:
            problems.append(f"undeclared removal: {path}")
    for path in declared_removed:
        if path not in delta["removed"]:
            problems.append(f"declared removed path {path} still exists in the source (stale declaration)")

    if problems:
        raise VerifyError(
            f"the declared transfer delta is not the actual delta between "
            f"{manifest['source']['path']} and {manifest['tree']}:\n  " + "\n  ".join(problems)
        )
    return delta


# ─── Format 2: policy-bound canonical stream ────────────────────────────────
#
# The format-2 digest hashes a canonical record stream — FILE and SYMLINK
# records, byte-wise sorted by normalized path — over an enumeration the
# policy file rules. The manifest binds the policy by SHA-256; this section
# mirrors cmd/nemo-runtime-digest's format-2 path exactly.

FORMAT_VERSION = 2


def match_element(pattern: str, s: str) -> bool:
    """Single-segment wildcard match: '*' and '?' stay within one element."""
    pb = sb = 0
    star = retry = -1
    while sb < len(s):
        if pb < len(pattern) and (pattern[pb] == "?" or pattern[pb] == s[sb]):
            pb += 1
            sb += 1
            continue
        if pb < len(pattern) and pattern[pb] == "*":
            star, retry, pb = pb, sb, pb + 1
            continue
        if star >= 0:
            pb, retry, sb = star + 1, retry + 1, retry
            continue
        return False
    while pb < len(pattern) and pattern[pb] == "*":
        pb += 1
    return pb == len(pattern)


def match_glob(pattern: str, path: str) -> bool:
    """Slash-separated glob: '**' crosses elements, '*' does not."""
    return _match_segments(pattern.split("/"), path.split("/"))


def _match_segments(pattern: list[str], path: list[str]) -> bool:
    while pattern:
        if pattern[0] == "**":
            return any(_match_segments(pattern[1:], path[i:]) for i in range(len(path) + 1))
        if not path or not match_element(pattern[0], path[0]):
            return False
        pattern, path = pattern[1:], path[1:]
    return not path


def generated_match(pattern: str, path: str) -> bool:
    """A trailing-slash pattern names a directory subtree; anything else must
    match the whole path — either way the subtree below it is generated."""
    pattern = pattern.rstrip("/")
    return match_glob(pattern, path) or match_glob(pattern + "/**", path)


class ProvenancePolicy:
    """The canonical-tree enumeration rules, loaded from the bound policy."""

    def __init__(self, data: dict):
        enum = data.get("enumeration") or {}
        self.excluded_dir_names = set(enum.get("excluded_dir_names") or [])
        self.excluded_dir_suffixes = enum.get("excluded_dir_suffixes") or []
        self.excluded_file_names = set(enum.get("excluded_file_names") or [])
        self.excluded_file_suffixes = enum.get("excluded_file_suffixes") or []
        self.generated_paths = enum.get("generated_paths") or []

    def is_generated(self, rel: str) -> bool:
        return any(generated_match(p, rel) for p in self.generated_paths)

    def prune_dir(self, name: str, rel: str) -> bool:
        """A directory drops out: excluded name, excluded suffix, or a
        generated subtree declared with a trailing slash."""
        if name in self.excluded_dir_names:
            return True
        if any(name.endswith(s) for s in self.excluded_dir_suffixes):
            return True
        return any(p.endswith("/") and generated_match(p, rel) for p in self.generated_paths)

    def skip_file(self, name: str, rel: str) -> bool:
        """A non-directory entry leaves enumeration: excluded name, excluded
        suffix, or generated path."""
        if name in self.excluded_file_names:
            return True
        if any(name.endswith(s) for s in self.excluded_file_suffixes):
            return True
        return self.is_generated(rel)


def read_policy(path: str) -> ProvenancePolicy:
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except OSError as e:
        raise VerifyError(f"the provenance policy {path}: {e}")
    except json.JSONDecodeError as e:
        raise VerifyError(f"{path} is not a valid provenance policy: {e}")
    declared = data.get("provenance_format_version")
    if declared != FORMAT_VERSION:
        raise VerifyError(
            f"{path} declares provenance_format_version {declared}; "
            f"this verifier implements {FORMAT_VERSION}"
        )
    return ProvenancePolicy(data)


def canonical_entries(root: str, policy: ProvenancePolicy) -> list[tuple[str, str, str, bool, str]]:
    """The tree's canonical objects: (path, kind, sha256, exec, target).

    Symlinked directories are entries, not traversals — WalkDir reports a
    link as a non-directory, so this walk must too. Anything that is neither
    a regular file nor a symlink is a malformed tree.
    """
    entries: list[tuple[str, str, str, bool, str]] = []
    for dirpath, dirnames, filenames in os.walk(root):
        kept: list[str] = []
        for name in dirnames:
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            if stat.S_ISLNK(os.lstat(full).st_mode):
                if not policy.skip_file(name, rel):
                    entries.append(("./" + rel, "symlink", "", False, _fs(os.readlink(full))))
                continue
            if not policy.prune_dir(name, rel):
                kept.append(name)
        dirnames[:] = kept
        for name in filenames:
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            if policy.skip_file(name, rel):
                continue
            st = os.lstat(full)
            normalized = "./" + rel
            if stat.S_ISREG(st.st_mode):
                entries.append((normalized, "file", file_digest(full), bool(st.st_mode & 0o111), ""))
            elif stat.S_ISLNK(st.st_mode):
                entries.append((normalized, "symlink", "", False, _fs(os.readlink(full))))
            else:
                raise VerifyError(
                    f"{normalized} is neither a regular file nor a symlink "
                    f"({stat.filemode(st.st_mode)}): the canonical tree does "
                    "not carry this object type"
                )
    # Byte-wise lexicographic path order — the canonical stream's ordering.
    entries.sort(key=lambda e: os.fsencode(e[0]))
    if len({e[0] for e in entries}) != len(entries):
        raise VerifyError("duplicate canonical path in enumeration")
    return entries


def _record(entry: tuple[str, str, str, bool, str]) -> str:
    path, kind, sha, exec_bit, target = entry
    if kind == "file":
        return f"FILE\t{path}\t{sha}\t{'x' if exec_bit else '-'}\n"
    return f"SYMLINK\t{path}\t{target}\n"


def _delta_identity(entry: tuple[str, str, str, bool, str]) -> str:
    path, kind, sha, exec_bit, target = entry
    if kind == "file":
        return f"file:{sha}:{'x' if exec_bit else '-'}"
    return "symlink:" + target


def digest_runtime_v2(root: str, policy: ProvenancePolicy) -> dict:
    """The format-2 identity — mirrors digestRuntimeV2."""
    if not os.path.isdir(root):
        raise VerifyError(f"the NeMo Relay runtime tree is missing at {root}")
    entries = canonical_entries(root, policy)
    files = sum(1 for e in entries if e[1] == "file")
    if files == 0:
        raise VerifyError(f"the NeMo Relay runtime tree at {root} contains no source files")
    outer = hashlib.sha256()
    for entry in entries:
        outer.update(_record(entry).encode("utf-8", "surrogateescape"))
    return {
        "nemo_runtime_sha256": outer.hexdigest(),
        "runtime_version": workspace_version(root),
        "tree": root,
        "file_count": files,
        "symlink_count": len(entries) - files,
    }


def _entry_map(root: str, policy: ProvenancePolicy) -> dict[str, tuple[str, str, str, bool, str]]:
    return {e[0].removeprefix("./"): e for e in canonical_entries(root, policy)}


def diff_trees_v2(source: str, vendored: str, policy: ProvenancePolicy) -> dict:
    """The typed format-2 delta: every object class under its own kind."""
    src = _entry_map(source, policy)
    vend = _entry_map(vendored, policy)
    delta: dict[str, list] = {
        "modified_files": [], "added_files": [], "removed_files": [],
        "added_symlinks": [], "removed_symlinks": [], "retargeted_symlinks": [],
        "retyped_paths": [], "mode_changes": [],
    }
    for path, src_entry in src.items():
        vend_entry = vend.get(path)
        if vend_entry is None:
            delta["removed_symlinks" if src_entry[1] == "symlink" else "removed_files"].append(path)
            continue
        if vend_entry[1] != src_entry[1]:
            delta["retyped_paths"].append(path)
            continue
        if src_entry[1] == "symlink":
            if vend_entry[4] != src_entry[4]:
                delta["retargeted_symlinks"].append(path)
        else:
            if vend_entry[2] != src_entry[2]:
                delta["modified_files"].append(path)
            elif vend_entry[3] != src_entry[3]:
                delta["mode_changes"].append(
                    {"path": path, "from": "x" if src_entry[3] else "-", "to": "x" if vend_entry[3] else "-"}
                )
    for path, vend_entry in vend.items():
        if path not in src:
            delta["added_symlinks" if vend_entry[1] == "symlink" else "added_files"].append(path)
    for key in ("modified_files", "added_files", "removed_files", "added_symlinks",
                "removed_symlinks", "retargeted_symlinks", "retyped_paths"):
        delta[key].sort()
    delta["mode_changes"].sort(key=lambda c: c["path"])
    return delta


def render_delta_block_v2(manifest: dict) -> str:
    """The typed format-2 delta as the canonical generated block."""
    delta = manifest.get("delta") or {}
    rows = []
    for kind, key in (
        ("modified file", "modified_files"),
        ("added file", "added_files"),
        ("removed file", "removed_files"),
        ("added symlink", "added_symlinks"),
        ("removed symlink", "removed_symlinks"),
        ("retargeted symlink", "retargeted_symlinks"),
        ("retyped", "retyped_paths"),
    ):
        rows.extend(f"| {kind} | `{p}` | |" for p in delta.get(key) or [])
    for change in delta.get("mode_changes") or []:
        rows.append(f"| mode change | `{change['path']}` | {change['from']} → {change['to']} |")
    if not rows:
        rows.append("| — | — | |")
    return "\n".join(
        [DELTA_BLOCK_BEGIN, "", "| Kind | Path | Detail |", "| --- | --- | --- |"]
        + rows + ["", DELTA_BLOCK_END]
    )


def render_source_block_v2(source: dict) -> str:
    """The format-2 source identity block: files, symlinks, canonical digest."""
    return "\n".join(
        [
            SOURCE_BLOCK_BEGIN,
            "",
            f"{source['file_count']} files, {source['symlink_count']} symlinks. Format-2 canonical digest (`FILE`/`SYMLINK` records,",
            "SHA-256, sorted byte-wise) over the source tree as it was copied, before any",
            "local modification:",
            "",
            "```text",
            source["sha256"],
            "```",
            "",
            SOURCE_BLOCK_END,
        ]
    )


def check_provenance_doc_v2(tree: str, manifest: dict) -> None:
    """The format-2 generated blocks must render the manifest exactly."""
    doc_path = os.path.join(tree, PROVENANCE_DOC)
    try:
        with open(doc_path, encoding="utf-8") as f:
            doc = f.read()
    except OSError as e:
        raise VerifyError(f"the provenance record {doc_path}: {e}")

    stale = []
    reconciled = splice_generated(
        doc, DELTA_BLOCK_BEGIN, DELTA_BLOCK_END, render_delta_block_v2(manifest), "delta block", doc_path
    )
    if reconciled != doc:
        stale.append("delta")
    source = manifest.get("source")
    if source:
        spliced = splice_generated(
            reconciled, SOURCE_BLOCK_BEGIN, SOURCE_BLOCK_END,
            render_source_block_v2(source), "source-identity block", doc_path,
        )
        if spliced != reconciled:
            stale.append("source-identity")
        reconciled = spliced
    elif SOURCE_BLOCK_BEGIN in reconciled:
        raise VerifyError(
            f"{doc_path} carries a generated source-identity block, but the "
            "manifest declares no source — the record and the declaration disagree"
        )
    if stale:
        which = " and ".join(stale) + (" blocks do" if len(stale) > 1 else " block does")
        raise VerifyError(
            f"{doc_path} is stale: its generated {which} not match the manifest — "
            "regenerate with `nemo-runtime-digest -manifest runtimes/nemo-transfer-manifest.json -update`"
        )


def verify_inventory_v2(manifest_path: str, manifest: dict, policy: ProvenancePolicy) -> None:
    """Format-2 structural claims — every declared forward-side path exists
    and none may name a generated artifact."""
    added_members = manifest.get("workspace_members_added") or []
    if added_members:
        members = declared_workspace_members(manifest["tree"])
        for member in added_members:
            if member not in members:
                raise VerifyError(
                    f"{manifest_path} declares workspace member {member!r}, but "
                    f"{manifest['tree']}/Cargo.toml does not list it"
                )
    delta = manifest.get("delta") or {}
    declared = []
    for key in ("modified_files", "added_files", "added_symlinks",
                "retargeted_symlinks", "retyped_paths"):
        declared.extend(delta.get(key) or [])
    declared.extend(c["path"] for c in delta.get("mode_changes") or [])
    for path in declared:
        trimmed = path.rstrip("/")
        if not trimmed:
            raise VerifyError(f"{manifest_path} declares an empty path")
        if policy.is_generated(trimmed):
            raise VerifyError(
                f"{manifest_path} declares {path!r}, but that path is a generated "
                "artifact under the provenance policy — generated output cannot "
                "be declared as source"
            )
        if not os.path.lexists(os.path.join(manifest["tree"], trimmed)):
            raise VerifyError(
                f"{manifest_path} declares {path!r}, but {manifest['tree']}/{trimmed} does not exist"
            )


def verify_delta_v2(manifest: dict, policy: ProvenancePolicy) -> dict:
    """The declared typed delta must equal the computed one, class for class."""
    delta = diff_trees_v2(manifest["source"]["path"], manifest["tree"], policy)
    declared = manifest.get("delta") or {}
    problems = []

    def check(name: str, actual: list, declared_paths: list, prefixes: bool) -> None:
        declared_sorted = sorted(declared_paths)
        for path in actual:
            covered = any(
                (path.startswith(d) if d.endswith("/") else path == d)
                if prefixes else path == d
                for d in declared_sorted
            )
            if not covered:
                problems.append(f"undeclared {name}: {path}")
        for d in declared_sorted:
            covers = any(
                (path.startswith(d) if d.endswith("/") else path == d)
                if prefixes else path == d
                for path in actual
            )
            if not covers:
                problems.append(f"declared {name} entry {d} matches no actual difference (stale declaration)")

    check("modified file", delta["modified_files"], declared.get("modified_files") or [], False)
    check("added file", delta["added_files"], declared.get("added_files") or [], True)
    check("removed file", delta["removed_files"], declared.get("removed_files") or [], False)
    check("added symlink", delta["added_symlinks"], declared.get("added_symlinks") or [], True)
    check("removed symlink", delta["removed_symlinks"], declared.get("removed_symlinks") or [], False)
    check("retargeted symlink", delta["retargeted_symlinks"], declared.get("retargeted_symlinks") or [], False)
    check("retyped path", delta["retyped_paths"], declared.get("retyped_paths") or [], False)

    declared_modes = {c["path"]: c for c in declared.get("mode_changes") or []}
    actual_modes = {c["path"]: c for c in delta["mode_changes"]}
    for path, actual in actual_modes.items():
        d = declared_modes.get(path)
        if d is None:
            problems.append(f"undeclared mode change: {path} ({actual['from']}→{actual['to']})")
        elif d.get("from") != actual["from"] or d.get("to") != actual["to"]:
            problems.append(
                f"mode change {path} declared as {d.get('from')}→{d.get('to')} "
                f"but computed {actual['from']}→{actual['to']}"
            )
    for path in declared_modes:
        if path not in actual_modes:
            problems.append(f"declared mode change {path} matches no actual difference (stale declaration)")

    if problems:
        raise VerifyError(
            f"the declared transfer delta is not the actual delta between "
            f"{manifest['source']['path']} and {manifest['tree']}:\n  " + "\n  ".join(sorted(problems))
        )
    return delta


def verify_manifest_v2(manifest_path: str, manifest: dict, require_source: bool) -> int:
    """The format-2 verification path — mirrors the Go tool's."""
    if not manifest.get("tree"):
        raise VerifyError(f"{manifest_path} declares no tree")
    policy_ref = manifest.get("policy")
    if not policy_ref:
        raise VerifyError(
            f"{manifest_path} declares provenance_format_version 2 but no "
            "policy — the enumeration rules must be bound"
        )
    for key in ("local_modifications", "added_paths", "removed_paths"):
        if manifest.get(key):
            raise VerifyError(
                f"{manifest_path} declares format 2 but uses the flat v1 "
                "delta fields — the typed delta object is required"
            )
    if manifest.get("delta") is None:
        raise VerifyError(f"{manifest_path} declares format 2 but no delta object")

    policy = read_policy(policy_ref["path"])
    if file_digest(policy_ref["path"]) != policy_ref.get("sha256"):
        raise VerifyError(
            f"{manifest_path} binds policy {policy_ref['path']} as {policy_ref.get('sha256')}, "
            f"but the file hashes {file_digest(policy_ref['path'])} — "
            "the enumeration rules do not match the declaration"
        )
    print(f"ok: policy {policy_ref['path']} {policy_ref['sha256']}")

    identity = digest_runtime_v2(manifest["tree"], policy)
    mismatches = []
    if manifest.get("runtime_version") != identity["runtime_version"]:
        mismatches.append(
            f"runtime_version: declared {manifest.get('runtime_version')!r}, "
            f"computed {identity['runtime_version']!r}"
        )
    if manifest.get("shipped_tree_sha256") != identity["nemo_runtime_sha256"]:
        mismatches.append(
            f"shipped_tree_sha256: declared {manifest.get('shipped_tree_sha256')}, "
            f"computed {identity['nemo_runtime_sha256']}"
        )
    if manifest.get("file_count") != identity["file_count"]:
        mismatches.append(
            f"file_count: declared {manifest.get('file_count')}, computed {identity['file_count']}"
        )
    if manifest.get("symlink_count") != identity["symlink_count"]:
        mismatches.append(
            f"symlink_count: declared {manifest.get('symlink_count')}, computed {identity['symlink_count']}"
        )
    if mismatches:
        raise VerifyError(
            f"{identity['tree']} does not match {manifest_path}:\n  " + "\n  ".join(mismatches)
            + f"\nregenerate with: go run ./cmd/nemo-runtime-digest -manifest {manifest_path} -update"
        )
    print(
        f"ok: {identity['tree']} {identity['nemo_runtime_sha256']} "
        f"({identity['file_count']} files, {identity['symlink_count']} symlinks, "
        f"{identity['runtime_version']}, format {FORMAT_VERSION})"
    )

    verify_inventory_v2(manifest_path, manifest, policy)
    verify_binaries(manifest_path, manifest)
    if manifest.get("binaries"):
        print(f"ok: {len(manifest['binaries'])} declared binaries have sources and declarations")

    check_provenance_doc_v2(manifest["tree"], manifest)
    print(f"ok: {PROVENANCE_DOC}'s generated blocks match the manifest")

    source = manifest.get("source")
    if not source:
        return 0
    if not os.path.exists(source["path"]):
        if require_source or source.get("required"):
            raise VerifyError(
                f"the declared source tree {source['path']} is not present — "
                "transfer-provenance qualification requires it"
            )
        print(
            f"note: source tree {source['path']} is not present; "
            "the declared source identity was not recomputed",
            file=sys.stderr,
        )
        return 0

    src_identity = digest_runtime_v2(source["path"], policy)
    source_mismatch = []
    if src_identity["nemo_runtime_sha256"] != source.get("sha256"):
        source_mismatch.append(
            f"sha256: declared {source.get('sha256')}, computed {src_identity['nemo_runtime_sha256']}"
        )
    if src_identity["file_count"] != source.get("file_count"):
        source_mismatch.append(
            f"file_count: declared {source.get('file_count')}, computed {src_identity['file_count']}"
        )
    if src_identity["symlink_count"] != source.get("symlink_count"):
        source_mismatch.append(
            f"symlink_count: declared {source.get('symlink_count')}, computed {src_identity['symlink_count']}"
        )
    if source_mismatch:
        raise VerifyError(
            f"source tree {source['path']} does not match its declared identity:\n  "
            + "\n  ".join(source_mismatch)
            + f"\nregenerate with: go run ./cmd/nemo-runtime-digest -manifest {manifest_path} -update"
        )
    print(
        f"ok: source {src_identity['tree']} {src_identity['nemo_runtime_sha256']} "
        f"({src_identity['file_count']} files, {src_identity['symlink_count']} symlinks)"
    )

    delta = verify_delta_v2(manifest, policy)
    print(
        f"ok: delta {len(delta['modified_files'])} modified, {len(delta['added_files'])} added files, "
        f"{len(delta['removed_files'])} removed files, {len(delta['added_symlinks'])} added links, "
        f"{len(delta['removed_symlinks'])} removed links, {len(delta['retargeted_symlinks'])} retargeted, "
        f"{len(delta['retyped_paths'])} retyped, {len(delta['mode_changes'])} mode changes — all declared"
    )
    return 0


def verify_manifest(path: str, require_source: bool = False) -> int:
    try:
        with open(path, encoding="utf-8") as f:
            manifest = json.load(f)
    except OSError as e:
        raise VerifyError(str(e))
    except json.JSONDecodeError as e:
        raise VerifyError(f"{path} is not a valid transfer manifest: {e}")
    version = manifest.get("provenance_format_version") or 1
    if not isinstance(version, int) or version < 0 or version > FORMAT_VERSION:
        raise VerifyError(
            f"{path} declares provenance_format_version {version}; "
            f"this verifier implements at most {FORMAT_VERSION} — "
            "refusing to reinterpret it"
        )
    if version == FORMAT_VERSION:
        return verify_manifest_v2(path, manifest, require_source)
    if (
        not (manifest.get("local_modifications") or manifest.get("added_paths") or manifest.get("removed_paths"))
        and manifest.get("delta") is not None
    ):
        raise VerifyError(
            f"{path} declares a typed delta without provenance_format_version "
            f"{FORMAT_VERSION} — set the version or use the flat fields"
        )
    if not manifest.get("tree"):
        raise VerifyError(f"{path} declares no tree")

    identity = digest_runtime(manifest["tree"])
    mismatches = []
    if manifest.get("runtime_version") != identity["runtime_version"]:
        mismatches.append(
            f"runtime_version: declared {manifest.get('runtime_version')!r}, "
            f"computed {identity['runtime_version']!r}"
        )
    if manifest.get("shipped_tree_sha256") != identity["nemo_runtime_sha256"]:
        mismatches.append(
            f"shipped_tree_sha256: declared {manifest.get('shipped_tree_sha256')}, "
            f"computed {identity['nemo_runtime_sha256']}"
        )
    if manifest.get("file_count") != identity["file_count"]:
        mismatches.append(
            f"file_count: declared {manifest.get('file_count')}, computed {identity['file_count']}"
        )
    if (manifest.get("excluded") or []) != identity["excluded"]:
        mismatches.append(
            f"excluded: declared {manifest.get('excluded')}, computed {identity['excluded']}"
        )
    if mismatches:
        raise VerifyError(
            f"{identity['tree']} does not match {path}:\n  " + "\n  ".join(mismatches)
        )
    print(
        f"ok: {identity['tree']} {identity['nemo_runtime_sha256']} "
        f"({identity['file_count']} files, {identity['runtime_version']})"
    )

    verify_inventory(path, manifest)
    print(
        f"ok: inventory {len(manifest.get('workspace_members_added') or [])} workspace members, "
        f"{len(manifest.get('local_modifications') or [])} modifications, "
        f"{len(manifest.get('added_paths') or [])} added paths"
    )

    verify_binaries(path, manifest)
    if manifest.get("binaries"):
        print(f"ok: {len(manifest['binaries'])} declared binaries have sources and declarations")

    check_provenance_doc(manifest["tree"], manifest)
    print(f"ok: {PROVENANCE_DOC}'s generated blocks match the manifest")

    source = manifest.get("source")
    if not source:
        return 0
    if not os.path.exists(source["path"]):
        print(
            f"note: source tree {source['path']} is not present; "
            "the declared source identity was not recomputed",
            file=sys.stderr,
        )
        return 0
    src_identity = digest_runtime(source["path"])
    if (
        src_identity["nemo_runtime_sha256"] != source.get("sha256")
        or src_identity["file_count"] != source.get("file_count")
    ):
        raise VerifyError(
            f"source tree {source['path']} does not match its declared identity: "
            f"declared {source.get('sha256')} ({source.get('file_count')} files), "
            f"computed {src_identity['nemo_runtime_sha256']} ({src_identity['file_count']} files)"
        )
    print(f"ok: source {src_identity['tree']} {src_identity['nemo_runtime_sha256']} ({src_identity['file_count']} files)")

    delta = verify_delta(manifest)
    print(
        f"ok: delta {len(delta['modified'])} modifications, {len(delta['added'])} added, "
        f"{len(delta['removed'])} removed — all declared"
    )
    return 0


def main(argv: list[str]) -> int:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default = os.path.normpath(os.path.join(script_dir, "..", "runtimes", "nemo-transfer-manifest.json"))
    require_source = "--require-source" in argv
    positional = [a for a in argv if a != "--require-source"]
    path = os.path.abspath(positional[0]) if positional else default
    # Manifest tree/source paths are relative to the repository root —
    # the manifest's parent is runtimes/, so the root is its grandparent.
    manifest_dir = os.path.dirname(path)
    repo_root = os.path.dirname(manifest_dir) if os.path.basename(manifest_dir) == "runtimes" else manifest_dir
    os.chdir(repo_root)
    try:
        return verify_manifest(path, require_source)
    except VerifyError as e:
        print(f"verify-nemo-transfer: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
